### ISSUE TITLE
some more projects provide modules

### ISSUE THREAD

**Issue by ChuanqiXu9** [kelteseth/arewemodulesyet#10]
[async_simple](https://github.com/alibaba/async_simple)'s module module: https://github.com/alibaba/async_simple/blob/main/modules/async_simple.cppm

[seastar](https://github.com/scylladb/seastar/tree/master)'s module: https://github.com/scylladb/seastar/blob/master/src/seastar.cc#L150

Both of the libraries are not on the list : (. So it might be better to use other properties (like github stars?) than vcpkg.

Also there is a project (not library as far as I know) [inifinity](https://github.com/infiniflow/infinity) use modules natively (we can get the usages at a random file under 'src', e,g., https://github.com/infiniflow/infinity/blob/main/src/network/buffer_writer.cppm). While it is not a library, I think it is a good example to give people more confidence.

And there is a high quality toy project using modules: https://github.com/davidstone/technical-machine, which is module native too.

**Comment by kelteseth** [comment]
1. Looks like both of these modules are not in vcpkg, so this is the reason why they are not in our list. At least for seastar there is an issue regarding vcpkg support https://github.com/scylladb/seastar/issues/1259. So I would prefere to have this upstream fixed, because sadly vcpkg is still the best way to know a popularity, because:
2. Not all c++ libraries use github, so there is no point on using stars (sadly). I know this is not perfect, but this is not that important anyway. If you have other ideas on how to better track popularity, please let me know :)
3. Yeah maybe a list of high quality projects that use modules would be nice!

**Comment by kelteseth** [comment]
This has been fixed by the work of @ChuanqiXu9 and some small tweaks by me
